artifact_uri: ./mlflowruns/2/8b86934328af436ba924b5d3edf84dba/artifacts
end_time: 1653762436646
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 8b86934328af436ba924b5d3edf84dba
run_uuid: 8b86934328af436ba924b5d3edf84dba
source_name: ''
source_type: 4
source_version: ''
start_time: 1653762431657
status: 3
tags: []
user_id: jabarnett
