artifact_uri: ./mlflowruns/2/b74805e48d4a4bcc88cee1f52866cbd4/artifacts
end_time: 1653762403753
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: b74805e48d4a4bcc88cee1f52866cbd4
run_uuid: b74805e48d4a4bcc88cee1f52866cbd4
source_name: ''
source_type: 4
source_version: ''
start_time: 1653762390561
status: 3
tags: []
user_id: jabarnett
