artifact_uri: ./mlflowruns/2/afef4fd3b6f748d3adff7dac18d08e2f/artifacts
end_time: 1653762650572
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: afef4fd3b6f748d3adff7dac18d08e2f
run_uuid: afef4fd3b6f748d3adff7dac18d08e2f
source_name: ''
source_type: 4
source_version: ''
start_time: 1653762643993
status: 3
tags: []
user_id: jabarnett
