artifact_uri: ./mlflowruns/2/ad568a4f200043db9eb34a2bfa158e4b/artifacts
end_time: 1653762575618
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: ad568a4f200043db9eb34a2bfa158e4b
run_uuid: ad568a4f200043db9eb34a2bfa158e4b
source_name: ''
source_type: 4
source_version: ''
start_time: 1653762569321
status: 3
tags: []
user_id: jabarnett
