artifact_uri: ./mlflowruns/2/72d751fbff6b40bab77b43f58b90cb28/artifacts
end_time: 1653762442073
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 72d751fbff6b40bab77b43f58b90cb28
run_uuid: 72d751fbff6b40bab77b43f58b90cb28
source_name: ''
source_type: 4
source_version: ''
start_time: 1653762440725
status: 3
tags: []
user_id: jabarnett
