artifact_uri: ./mlflowruns/2/3cf9b02d4a3a4a5c910616cc461cde9a/artifacts
end_time: 1653762589491
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 3cf9b02d4a3a4a5c910616cc461cde9a
run_uuid: 3cf9b02d4a3a4a5c910616cc461cde9a
source_name: ''
source_type: 4
source_version: ''
start_time: 1653762575639
status: 3
tags: []
user_id: jabarnett
