artifact_uri: ./mlflowruns/2/7c57f6dd0eb244bda52370f555665da5/artifacts
end_time: 1653762593482
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 7c57f6dd0eb244bda52370f555665da5
run_uuid: 7c57f6dd0eb244bda52370f555665da5
source_name: ''
source_type: 4
source_version: ''
start_time: 1653762589516
status: 3
tags: []
user_id: jabarnett
