artifact_uri: ./mlflowruns/3/6ab4be6661494ce580adc1f18de05108/artifacts
end_time: 1653864722338
entry_point_name: ''
experiment_id: '3'
lifecycle_stage: active
name: ''
run_id: 6ab4be6661494ce580adc1f18de05108
run_uuid: 6ab4be6661494ce580adc1f18de05108
source_name: ''
source_type: 4
source_version: ''
start_time: 1653864718445
status: 3
tags: []
user_id: jabarnett
