artifact_uri: ./mlflowruns/3/f7f1fed40edc44fbb07f68de539daf78/artifacts
end_time: 1653864708534
entry_point_name: ''
experiment_id: '3'
lifecycle_stage: active
name: ''
run_id: f7f1fed40edc44fbb07f68de539daf78
run_uuid: f7f1fed40edc44fbb07f68de539daf78
source_name: ''
source_type: 4
source_version: ''
start_time: 1653864702505
status: 3
tags: []
user_id: jabarnett
