artifact_uri: ./mlflowruns/2/3f92262946c34015abbba2ba403dbdf4/artifacts
end_time: 1653762704886
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 3f92262946c34015abbba2ba403dbdf4
run_uuid: 3f92262946c34015abbba2ba403dbdf4
source_name: ''
source_type: 4
source_version: ''
start_time: 1653762696999
status: 3
tags: []
user_id: jabarnett
