artifact_uri: ./mlflowruns/2/65b57b47f3a94f999aaadff2296b3a01/artifacts
end_time: 1653762607780
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 65b57b47f3a94f999aaadff2296b3a01
run_uuid: 65b57b47f3a94f999aaadff2296b3a01
source_name: ''
source_type: 4
source_version: ''
start_time: 1653762607243
status: 3
tags: []
user_id: jabarnett
