artifact_uri: ./mlflowruns/2/a64bc0ac13da4500879ba2e25ebdd171/artifacts
end_time: 1653762658226
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: a64bc0ac13da4500879ba2e25ebdd171
run_uuid: a64bc0ac13da4500879ba2e25ebdd171
source_name: ''
source_type: 4
source_version: ''
start_time: 1653762657986
status: 3
tags: []
user_id: jabarnett
