artifact_uri: ./mlflowruns/2/6fb9bd283a5f443f97424b3c6c59af6a/artifacts
end_time: 1653762386912
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 6fb9bd283a5f443f97424b3c6c59af6a
run_uuid: 6fb9bd283a5f443f97424b3c6c59af6a
source_name: ''
source_type: 4
source_version: ''
start_time: 1653762379193
status: 3
tags: []
user_id: jabarnett
