artifact_uri: ./mlflowruns/2/f1377d8c90434c1eaa714bcfdbaa7240/artifacts
end_time: 1653762479467
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: f1377d8c90434c1eaa714bcfdbaa7240
run_uuid: f1377d8c90434c1eaa714bcfdbaa7240
source_name: ''
source_type: 4
source_version: ''
start_time: 1653762476825
status: 3
tags: []
user_id: jabarnett
