artifact_uri: ./mlflowruns/2/3b94a46767ec40a79bbfc4f356bffe48/artifacts
end_time: 1653762746473
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 3b94a46767ec40a79bbfc4f356bffe48
run_uuid: 3b94a46767ec40a79bbfc4f356bffe48
source_name: ''
source_type: 4
source_version: ''
start_time: 1653762738349
status: 3
tags: []
user_id: jabarnett
