artifact_uri: ./mlflowruns/2/af58defdc3bf42e39c211fccf293c9bb/artifacts
end_time: 1653762696974
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: af58defdc3bf42e39c211fccf293c9bb
run_uuid: af58defdc3bf42e39c211fccf293c9bb
source_name: ''
source_type: 4
source_version: ''
start_time: 1653762692278
status: 3
tags: []
user_id: jabarnett
