artifact_uri: ./mlflowruns/3/d101f5901cf543e8b9c0a891ef4e1b17/artifacts
end_time: 1653864718431
entry_point_name: ''
experiment_id: '3'
lifecycle_stage: active
name: ''
run_id: d101f5901cf543e8b9c0a891ef4e1b17
run_uuid: d101f5901cf543e8b9c0a891ef4e1b17
source_name: ''
source_type: 4
source_version: ''
start_time: 1653864708554
status: 3
tags: []
user_id: jabarnett
