artifact_uri: ./mlflowruns/2/cccdc8fc558d40dbb068de6c2e17846c/artifacts
end_time: 1653762720391
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: cccdc8fc558d40dbb068de6c2e17846c
run_uuid: cccdc8fc558d40dbb068de6c2e17846c
source_name: ''
source_type: 4
source_version: ''
start_time: 1653762719033
status: 3
tags: []
user_id: jabarnett
