artifact_uri: ./mlflowruns/3/867290169d1d4eeb8ea7be7dc7c8a2fc/artifacts
end_time: 1653902495948
entry_point_name: ''
experiment_id: '3'
lifecycle_stage: active
name: ''
run_id: 867290169d1d4eeb8ea7be7dc7c8a2fc
run_uuid: 867290169d1d4eeb8ea7be7dc7c8a2fc
source_name: ''
source_type: 4
source_version: ''
start_time: 1653902486183
status: 3
tags: []
user_id: jabarnett
