artifact_uri: ./mlflowruns/2/c85362e95a8546d5aa4af4d5de3b0102/artifacts
end_time: 1653762446623
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: c85362e95a8546d5aa4af4d5de3b0102
run_uuid: c85362e95a8546d5aa4af4d5de3b0102
source_name: ''
source_type: 4
source_version: ''
start_time: 1653762442084
status: 3
tags: []
user_id: jabarnett
