artifact_uri: ./mlflowruns/2/ed40be2e41fb4a79a6ae58eb4933d1e6/artifacts
end_time: 1653762528938
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: ed40be2e41fb4a79a6ae58eb4933d1e6
run_uuid: ed40be2e41fb4a79a6ae58eb4933d1e6
source_name: ''
source_type: 4
source_version: ''
start_time: 1653762509813
status: 3
tags: []
user_id: jabarnett
