artifact_uri: ./mlflowruns/2/4a0d86cbea75437dab27b7fcaba0d0d2/artifacts
end_time: 1653762692245
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 4a0d86cbea75437dab27b7fcaba0d0d2
run_uuid: 4a0d86cbea75437dab27b7fcaba0d0d2
source_name: ''
source_type: 4
source_version: ''
start_time: 1653762690313
status: 3
tags: []
user_id: jabarnett
