artifact_uri: ./mlflowruns/3/4100d69f3b5b4869bad36f5ab79a27a4/artifacts
end_time: 1653902480235
entry_point_name: ''
experiment_id: '3'
lifecycle_stage: active
name: ''
run_id: 4100d69f3b5b4869bad36f5ab79a27a4
run_uuid: 4100d69f3b5b4869bad36f5ab79a27a4
source_name: ''
source_type: 4
source_version: ''
start_time: 1653902471603
status: 3
tags: []
user_id: jabarnett
