artifact_uri: ./mlflowruns/2/e1222aca93d940eab07bb7e86a7e49e9/artifacts
end_time: 1653762465606
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: e1222aca93d940eab07bb7e86a7e49e9
run_uuid: e1222aca93d940eab07bb7e86a7e49e9
source_name: ''
source_type: 4
source_version: ''
start_time: 1653762458293
status: 3
tags: []
user_id: jabarnett
