artifact_uri: ./mlflowruns/2/d7d72d5d91ec435cbfd14bd208a1b927/artifacts
end_time: 1653762425278
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: d7d72d5d91ec435cbfd14bd208a1b927
run_uuid: d7d72d5d91ec435cbfd14bd208a1b927
source_name: ''
source_type: 4
source_version: ''
start_time: 1653762417651
status: 3
tags: []
user_id: jabarnett
