artifact_uri: ./mlflowruns/2/650c6d12d9884fffa6aa7b2469defe50/artifacts
end_time: 1653762657962
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
name: ''
run_id: 650c6d12d9884fffa6aa7b2469defe50
run_uuid: 650c6d12d9884fffa6aa7b2469defe50
source_name: ''
source_type: 4
source_version: ''
start_time: 1653762650594
status: 3
tags: []
user_id: jabarnett
