artifact_uri: ./mlflowruns/3/d979779db7474ea29ac5ecb220b0c002/artifacts
end_time: 1653865042598
entry_point_name: ''
experiment_id: '3'
lifecycle_stage: active
name: ''
run_id: d979779db7474ea29ac5ecb220b0c002
run_uuid: d979779db7474ea29ac5ecb220b0c002
source_name: ''
source_type: 4
source_version: ''
start_time: 1653865033906
status: 3
tags: []
user_id: jabarnett
