artifact_uri: ./mlflowruns/3/ad714de6db9e4e6d9bb8e366b0d9e407/artifacts
end_time: 1653865612511
entry_point_name: ''
experiment_id: '3'
lifecycle_stage: active
name: ''
run_id: ad714de6db9e4e6d9bb8e366b0d9e407
run_uuid: ad714de6db9e4e6d9bb8e366b0d9e407
source_name: ''
source_type: 4
source_version: ''
start_time: 1653865602429
status: 3
tags: []
user_id: jabarnett
